 POST http://localhost:3000/reports
 Content-Type: application/json


 {
  "make":"Toyota",
  "model":"Corolla",
  "year":1980,
  "mileage": 10000,
  "lng": 0,
  "lat": 0,
  "price": 500000
 }

### Approve an existing report
 PATCH http://localhost:3000/reports/2
 Content-Type: application/json

 {
  "approved":true
 }


### Get an Estimate Price of the car
GET http://localhost:3000/reports?make=Toyota&model=corolla&lng=0&lat=0&mileage=20000&year=1990



 
